export const fakeData = [
  {
    // 质量日报固定数据
    // 指令日报原料
    // itemRowSpan: 分析项目合并行
    // sampleRowSpan:原料名称与罐号/批号合并行
    limisRawMaterial: [
      { key: 1, sampleRowSpan: 11, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '密度（20℃）/（kg/m3）', nameSearchValue: ['密度(20℃)'] },
      { key: 2, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 3, name: '初馏点', nameSearchValue: ['初馏点'] },
      { key: 3, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 0, name: '馏程50%', nameSearchValue: ['馏程50%'] },
      { key: 4, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 0, name: '终馏点', nameSearchValue: ['终馏点'] },
      { key: 5, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 5, name: '烷烃（P）含量', nameSearchValue: ['烷烃'] },
      { key: 6, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '正构烷烃（n-P）含量', nameSearchValue: ['正构烷烃'] },
      { key: 7, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '烯烃（O）含量', nameSearchValue: ['烯烃'] },
      { key: 8, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '芳香烃（A）含量', nameSearchValue: ['芳烃'] },
      { key: 9, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '环烷烃（N）含量', nameSearchValue: ['环烷烃'] },
      { key: 10, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 11, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '含氧化合物/（mg/kg）', nameSearchValue: ['氧化物'] },
      { key: 12, sampleRowSpan: 5, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烷烃/ %（体积分数）', nameSearchValue: ['总烷烃'] },
      { key: 13, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烯烃/ %（体积分数）', nameSearchValue: ['总烯烃'] },
      { key: 14, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '丙烷/%+正丁烷/%（体积分数）', nameSearchValue: ['丙烷+正丁烷'] },
      { key: 15, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '碳五及碳五以上/%（体积分数）', nameSearchValue: ['C5及以上'] },
      { key: 16, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 17, sampleRowSpan: 6, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 5, name: '烷烃（P）含量', nameSearchValue: ['烷烃'] },
      { key: 18, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '正构烷烃（n-P）含量', nameSearchValue: ['正构烷烃'] },
      { key: 19, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '烯烃（O）含量', nameSearchValue: ['烯烃'] },
      { key: 20, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '芳香烃（A）含量', nameSearchValue: ['芳烃'] },
      { key: 21, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '环烷烃（N）含量', nameSearchValue: ['环烷烃'] },
      { key: 22, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油', '碳五拔头油'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['硫'] },
      { key: 23, sampleRowSpan: 6, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: null, name: '芳烃指数（BMCI）', nameSearchValue: ['芳烃指数（BMCI）'] },
      { key: 24, sampleRowSpan: 0, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: null, name: '密度（20℃）/（kg/m3）', nameSearchValue: ['密度（20℃）/（kg/m3）'] },
      { key: 25, sampleRowSpan: 0, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: '馏程/℃', itemRowSpan: 3, name: '初馏点', nameSearchValue: ['初馏点'] },
      { key: 26, sampleRowSpan: 0, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: '馏程/℃', itemRowSpan: 0, name: '90%回收温度', nameSearchValue: ['90%回收温度'] },
      { key: 27, sampleRowSpan: 0, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: '馏程/℃', itemRowSpan: 0, name: '终馏点', nameSearchValue: ['终馏点'] },
      { key: 28, sampleRowSpan: 0, sampleName: '加氢尾油', sampleSearchValue: ['加氢尾油'], item: null, name: '硫含量/（mg/kg）', nameSearchValue: ['硫含量/（mg/kg）'] },
      { key: 29, sampleRowSpan: 4, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '乙烷含量/%（体积分数）', nameSearchValue: ['乙烷'] },
      { key: 30, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '碳三及以上烃类/ %（体积分数）', nameSearchValue: ['C3和C3以上烃类'] },
      { key: 31, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '不饱和烃类/ %（体积分数）', nameSearchValue: ['不饱和烃类'] },
      { key: 32, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 33, sampleRowSpan: 4, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '丙烷/ %（体积分数）', nameSearchValue: ['丙烷'] },
      { key: 34, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '总烯烃/ %（体积分数）', nameSearchValue: ['总烯烃'] },
      { key: 35, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: 'C5及C5以上/ %（体积分数）', nameSearchValue: ['C5及以上'] },
      { key: 36, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 37, sampleRowSpan: 4, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '氢气/ %（体积分数）', nameSearchValue: ['氢气'] },
      { key: 38, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '氮气/%（体积分数）', nameSearchValue: ['氮气'] },
      { key: 39, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '甲烷/%（体积分数）', nameSearchValue: ['甲烷'] },
      { key: 40, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '乙烷+乙烯/ %（体积分数）', nameSearchValue: ['乙烷+乙烯'] },
      { key: 41, sampleRowSpan: 7, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '乙烯含量/%（体积分数）', nameSearchValue: ['乙烯'] },
      { key: 42, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '丙烷含量/ %（体积分数）', nameSearchValue: ['丙烷'] },
      { key: 43, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '丙烯含量/ %（体积分数）', nameSearchValue: ['丙烯'] },
      { key: 44, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: 'C4和C4以上含量/ %（体积分数）', nameSearchValue: ['C4和C4以上含量'] },
      { key: 45, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '一氧化碳含量/ %（体积分数）', nameSearchValue: ['一氧化碳含量'] },
      { key: 46, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '二氧化碳含量/ %（体积分数）', nameSearchValue: ['二氧化碳含量'] },
      { key: 47, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '总硫含量/ %（体积分数）', nameSearchValue: ['总硫'] },
      { key: 48, sampleRowSpan: 6, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '全水分Mt/%', nameSearchValue: ['全水分Mt/%'] },
      { key: 49, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥基灰分Ad/％', nameSearchValue: ['干燥基灰分Ad/％'] },
      { key: 50, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥无灰基挥发分Vdaf/%', nameSearchValue: ['干燥无灰基挥发分Vdaf/%'] },
      { key: 51, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '空干基高位发热量Qgr，ad/kcal/kg', nameSearchValue: ['空干基高位发热量Qgr，ad/kcal/kg'] },
      { key: 52, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '收到基低位热值Qnet，ar/kcal/kg', nameSearchValue: ['收到基低位热值Qnet，ar/kcal/kg'] },
      { key: 53, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥基全硫St，d/%', nameSearchValue: ['干燥基全硫St，d/%'] },
    ],
    // 质量日报 -> 中控 -> 馏出口
    outlet: [
      { key: 1, locationRowSpan: 16, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['一氧化碳'], name: '一氧化碳/（ml/m³）' },
      { key: 2, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['二氧化碳'], name: '二氧化碳/（ml/m³）' },
      { key: 3, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['氢气'], name: '氢气/ %（体积分数）' },
      { key: 4, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['乙烷+乙烯'], name: '乙烷+乙烯/ %（体积分数）' },
      { key: 5, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['乙烯'], name: '乙烯含量/%（体积分数） ' },
      { key: 6, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['碳三及以上馏分'], name: 'C3和C3以上含量/（ml/m3）' },
      { key: 7, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['乙炔'], name: '乙炔含量/（ml/m3）' },
      { key: 8, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['硫'], name: '硫含量/（mg/kg）' },
      { key: 9, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['丙烯'], name: '丙烯含量/ %（体积分数）' },
      { key: 10, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['甲基乙炔+丙二烯'], name: '甲基乙炔+丙二烯含量/ %（质量分数）' },
      { key: 11, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['丁二烯'], name: '丁烯/ %（质量分数）' },
      { key: 12, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['硫'], name: '碳五及以上/ %（质量分数）' },
      { key: 13, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['C3'], name: '碳三/ %（质量分数）' },
      { key: 14, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['丁二烯'], name: '丁二烯/ %（质量分数）' },
      { key: 15, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['丁烯'], name: '丁烯/ %（质量分数）' },
      { key: 16, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['C5及C5以上'], name: '碳五及以上/ %（质量分数）' },
      { key: 166, locationRowSpan: 6, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 4, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['1,3-丁二烯'], name: '丁二烯含量/ %（质量分数）' },
      { key: 17, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['总炔'], name: '总炔含量/（mg/kg）' },
      { key: 18, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['乙烯基乙炔'], name: '乙烯基乙炔含量/（mg/kg）' },
      { key: 19, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['TBC含量'], name: 'TBC含量/（mg/kg）' },
      { key: 20, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 2, sampleSearchValue: ['抽余C4'], sampleName: '抽余碳四', item: null, nameSearchValue: ['1,3-丁二烯'], name: '1,3-丁二烯含量/（mg/kg）' },
      { key: 21, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['抽余C4'], sampleName: '抽余碳四', item: null, nameSearchValue: ['乙腈'], name: '乙腈含量/（mg/kg）' },
      { key: 22, locationRowSpan: 4, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 2, sampleSearchValue: ['MTBE产品'], sampleName: 'MTBE', item: null, nameSearchValue: ['甲基叔丁基醚+甲基仲丁基醚+C5'], name: '甲基叔丁基醚+‎甲基仲丁基‎醚‎/ %（质量分数）' },
      { key: 23, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 0, sampleSearchValue: ['MTBE产品'], sampleName: 'MTBE', item: null, nameSearchValue: ['甲醇'], name: '甲醇/ %（质量分数）' },
      { key: 24, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 2, sampleSearchValue: ['丁烯-1产品'], sampleName: '丁烯-1', item: null, nameSearchValue: ['1-丁烯'], name: '丁烯-1纯度/ %（质量分数）' },
      { key: 25, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 0, sampleSearchValue: ['丁烯-1产品'], sampleName: '丁烯-1', item: null, nameSearchValue: ['1,3-丁二烯+丙二烯'], name: '丁二烯+丙二烯/（mg/kg）' },
      { key: 26, locationRowSpan: 4, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 2, sampleSearchValue: ['苯产品'], sampleName: '苯', item: null, nameSearchValue: ['苯'], name: '纯度/%（质量分数）' },
      { key: 27, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 0, sampleSearchValue: ['苯产品'], sampleName: '苯', item: null, nameSearchValue: ['苯结晶点'], name: '结晶点/℃' },
      { key: 28, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 1, sampleSearchValue: ['甲苯产品'], sampleName: '甲苯', item: null, nameSearchValue: ['甲苯'], name: '纯度/%（质量分数）' },
      { key: 29, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 1, sampleSearchValue: ['混合二甲苯产品'], sampleName: '混合二甲苯', item: null, nameSearchValue: ['乙苯+二甲苯'], name: '二甲苯/%（质量分数）' },
      { key: 30, locationRowSpan: 3, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 3, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['C5'], name: '碳五/ %（质量分数）' },
      { key: 31, locationRowSpan: 0, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 0, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['C9以上芳烃'], name: '碳九及以上芳烃/ %(质量分数)' },
      { key: 32, locationRowSpan: 0, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 0, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['溴价'], name: '溴价/（g溴/100g油）' },
      { key: 33, locationRowSpan: 13, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 6, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 34, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['异戊二烯'], name: '异戊二烯/ %（质量分数）' },
      { key: 35, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['炔烃'], name: '总炔/（mg/kg）' },
      { key: 36, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['二甲基甲酰胺'], name: '二甲基甲酰胺/（mg/kg）' },
      { key: 37, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['硫'], name: '硫含量/（mg/kg）' },
      { key: 38, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['水'], name: '水含量/ %（质量分数）' },
      { key: 39, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 4, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 40, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['间戊二烯'], name: '间戊二烯含量/ %（质量分数）' },
      { key: 41, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['环戊二烯+双环戊二烯'], name: '环戊二烯+双环戊二烯含量/ %（质量分数）' },
      { key: 42, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['水'], name: '水含量/ %（质量分数）' },
      { key: 43, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 3, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 44, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['双环戊二烯'], name: '双环戊二烯/ %（质量分数）' },
      { key: 45, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['碳六及以下'], name: 'C6及以下/ %（质量分数）' },
      { key: 46, locationRowSpan: 11, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 6, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['乙二醇'], name: '乙二醇纯度/%（质量分数）' },
      { key: 47, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['水'], name: '水含量/%（质量分数）' },
      { key: 48, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 3, nameSearchValue: ['紫外透过率(220nm)'], name: '220nm' },
      { key: 49, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 0, nameSearchValue: ['紫外透过率(275nm)'], name: '275nm' },
      { key: 50, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 0, nameSearchValue: ['紫外透过率(350nm)'], name: '350nm' },
      { key: 51, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['醛(以甲醛计)'], name: '醛含量/（mg/kg）' },
      { key: 52, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 3, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['乙二醇'], name: '乙二醇含量/%（质量分数）' },
      { key: 53, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['三乙二醇'], name: '三乙二醇含量/%（质量分数）' },
      { key: 54, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['水'], name: '水含量/%（质量分数）' },
      { key: 55, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 2, sampleSearchValue: ['三乙二醇产品'], sampleName: '三乙二醇', item: null, nameSearchValue: ['二乙二醇'], name: '二乙二醇含量/%（质量分数）' },
      { key: 56, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['三乙二醇产品'], sampleName: '三乙二醇', item: null, nameSearchValue: ['多乙二醇'], name: '多乙二醇含量/%（质量分数）' },
    ],
    // 质量日报 -> 中控 -> 聚合装置中控质量情况
    polymerizer: [
      { key: 1, locationRowSpan: 6, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 2, sampleSearchValue: ['F-3001罐粉料'], sampleName: 'F-3001罐粉料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 2, locationRowSpan: 0, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 0, sampleSearchValue: ['F-3001罐粉料'], sampleName: 'F-3001罐粉料', nameSearchValue: ['密度'], name: '密度/（g/cm3）' },
      { key: 3, locationRowSpan: 0, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 2, sampleSearchValue: ['HDPE粉料'], sampleName: 'HDPE粉料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 4, locationRowSpan: 0, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 0, sampleSearchValue: ['HDPE粉料'], sampleName: 'HDPE粉料', nameSearchValue: ['密度'], name: '密度/（g/cm3） ' },
      { key: 5, locationRowSpan: 0, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 2, sampleSearchValue: ['HDPE粒料'], sampleName: 'HDPE粒料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 6, locationRowSpan: 0, locationSearchValue: ['HDPE'], location: 'HDPE装置', sampleRowSpan: 0, sampleSearchValue: ['HDPE粒料'], sampleName: 'HDPE粒料', nameSearchValue: ['密度'], name: '密度/（g/cm3）' },
      { key: 7, locationRowSpan: 2, locationSearchValue: ['LLDPE'], location: 'LLDPE装置', sampleRowSpan: 1, sampleSearchValue: ['LLDPE粉料'], sampleName: '粒料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 8, locationRowSpan: 0, locationSearchValue: ['LLDPE'], location: 'LLDPE装置', sampleRowSpan: 1, sampleSearchValue: ['LLDPE粉料'], sampleName: '粒料', nameSearchValue: ['密度'], name: '密度/（g/cm3）' },
      { key: 9, locationRowSpan: 3, locationSearchValue: ['ST-PP'], location: 'STPP装置', sampleRowSpan: 2, sampleSearchValue: ['聚丙烯粉料'], sampleName: '粉料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 10, locationRowSpan: 0, locationSearchValue: ['ST-PP'], location: 'STPP装置', sampleRowSpan: 0, sampleSearchValue: ['聚丙烯粉料'], sampleName: '粉料', nameSearchValue: ['密度'], name: '乙烯含量/%' },
      { key: 11, locationRowSpan: 0, locationSearchValue: ['ST-PP'], location: 'STPP装置', sampleRowSpan: 1, sampleSearchValue: ['聚丙烯粒料'], sampleName: '粒料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 12, locationRowSpan: 5, locationSearchValue: ['JPP'], location: 'JPP装置', sampleRowSpan: 1, sampleSearchValue: ['聚丙烯粉末'], sampleName: '聚丙烯粉末', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 13, locationRowSpan: 0, locationSearchValue: ['JPP'], location: 'JPP装置', sampleRowSpan: 3, sampleSearchValue: ['聚丙烯粉料'], sampleName: '聚丙烯粉料', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
      { key: 14, locationRowSpan: 0, locationSearchValue: ['JPP'], location: 'JPP装置', sampleRowSpan: 0, sampleSearchValue: ['聚丙烯粉料'], sampleName: '聚丙烯粉料', nameSearchValue: ['乙烯含量'], name: '乙烯含量/%' },
      { key: 15, locationRowSpan: 0, locationSearchValue: ['JPP'], location: 'JPP装置', sampleRowSpan: 0, sampleSearchValue: ['聚丙烯粉料'], sampleName: '聚丙烯粉料', nameSearchValue: ['嵌段乙烯含量'], name: '嵌段乙烯含量/%' },
      { key: 16, locationRowSpan: 0, locationSearchValue: ['JPP'], location: 'JPP装置', sampleRowSpan: 1, sampleSearchValue: ['PP颗粒'], sampleName: 'PP颗粒', nameSearchValue: ['熔体质量流动速率'], name: '熔体质量流动速率/(g/10min)' },
    ],
    limisProduct: [
      { key: 1, sampleRowSpan: 3, sampleName: '异戊二烯', sampleSearchValue: ['工业用异戊二烯'], item: null, name: '异戊二烯/ %（质量分数）', nameSearchValue: ['异戊二烯'] },
      { key: 2, sampleRowSpan: 0, sampleName: '异戊二烯', sampleSearchValue: ['工业用异戊二烯'], item: null, name: '硫含量/（mg/kg）', nameSearchValue: ['环戊二烯'] },
      { key: 3, sampleRowSpan: 0, sampleName: '异戊二烯', sampleSearchValue: ['工业用异戊二烯'], item: null, name: '水含量/ %（质量分数）', nameSearchValue: ['水'] },
      { key: 4, sampleRowSpan: 2, sampleName: '间戊二烯', sampleSearchValue: ['工业用间戊二烯'], item: null, name: '间戊二烯含量/ %（质量分数）', nameSearchValue: ['间戊二烯'] },
      { key: 5, sampleRowSpan: 0, sampleName: '间戊二烯', sampleSearchValue: ['工业用间戊二烯'], item: null, name: '水含量/ %（质量分数）', nameSearchValue: ['水'] },
      { key: 6, sampleRowSpan: 2, sampleName: '双环戊二烯', sampleSearchValue: ['工业用双环戊二烯'], item: null, name: '色度/（Hazen单位-铂-钴号）', nameSearchValue: ['色度(Pt-Co)'] },
      { key: 7, sampleRowSpan: 0, sampleName: '双环戊二烯', sampleSearchValue: ['工业用双环戊二烯'], item: null, name: '双环戊二烯含量/ %（质量分数）', nameSearchValue: ['双环戊二烯'] },
      { key: 8, sampleRowSpan: 2, sampleName: '丁二烯', sampleSearchValue: ['工业用丁二烯'], item: null, name: '丁二烯含量/ %（质量分数）', nameSearchValue: ['1,3-丁二烯'] },
      { key: 9, sampleRowSpan: 0, sampleName: '丁二烯', sampleSearchValue: ['工业用丁二烯'], item: null, name: 'TBC含量/（mg/kg）', nameSearchValue: ['阻聚剂TBC'] },
      { key: 10, sampleRowSpan: 2, sampleName: 'MTBE', sampleSearchValue: ['工业用甲基叔丁基醚(互供）'], item: null, name: '甲基叔丁基醚+‎甲基仲丁基‎醚‎/ %（质量分数）', nameSearchValue: ['甲基叔丁基醚+甲基仲丁基醚'] },
      { key: 11, sampleRowSpan: 0, sampleName: 'MTBE', sampleSearchValue: ['工业用甲基叔丁基醚(互供）'], item: null, name: '甲醇/ %（质量分数）', nameSearchValue: ['甲醇'] },
      { key: 12, sampleRowSpan: 5, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烷烃/ %（体积分数）', nameSearchValue: ['总烷烃'] },
      { key: 13, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烯烃/ %（体积分数）', nameSearchValue: ['总烯烃'] },
      { key: 14, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '丙烷/%+正丁烷/%（体积分数）', nameSearchValue: ['丙烷+正丁烷'] },
      { key: 15, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '碳五及碳五以上/%（体积分数）', nameSearchValue: ['C5及以上'] },
      { key: 16, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 17, sampleRowSpan: 1, sampleName: '丁烯-1', sampleSearchValue: ['工业用1-丁烯'], item: null, name: '丁烯-1纯度/ %（质量分数）', nameSearchValue: ['丁烯-1'] },
      { key: 18, sampleRowSpan: 2, sampleName: '苯', sampleSearchValue: ['石油苯'], item: null, name: '苯纯度/ %（质量分数）', nameSearchValue: ['苯(纯度)'] },
      { key: 19, sampleRowSpan: 0, sampleName: '苯', sampleSearchValue: ['石油苯'], item: null, name: '结晶点（干基）/℃', nameSearchValue: ['苯结晶点'] },
      { key: 20, sampleRowSpan: 1, sampleName: '甲苯', sampleSearchValue: ['石油甲苯'], item: null, name: '甲苯纯度/ %（质量分数）', nameSearchValue: ['甲苯纯度'] },
      { key: 21, sampleRowSpan: 1, sampleName: '混合二甲苯', sampleSearchValue: ['混合二甲苯'], item: null, name: '二甲苯纯度/ %（质量分数）', nameSearchValue: ['纯度（乙苯+二甲苯）'] },
      { key: 22, sampleRowSpan: 2, sampleName: '环氧乙烷', sampleSearchValue: ['工业用环氧乙烷'], item: null, name: '环氧乙烷的质量分数/%', nameSearchValue: ['纯度'] },
      { key: 23, sampleRowSpan: 0, sampleName: '环氧乙烷', sampleSearchValue: ['工业用环氧乙烷'], item: null, name: '总醛（以乙醛计）的质量分数/%', nameSearchValue: ['醛含量(乙醛计)'] },
      { key: 24, sampleRowSpan: 7, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: null, name: '乙二醇纯度/%（质量分数）', nameSearchValue: ['纯度'] },
      { key: 25, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: '沸程/℃', itemRowSpan: 2, name: '初馏点', nameSearchValue: ['初馏点'] },
      { key: 26, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: '沸程/℃', itemRowSpan: 0, name: '干点', nameSearchValue: ['干点'] },
      { key: 27, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: null, name: '醛（以甲醛计）/%（质量分数）', nameSearchValue: ['醛(以甲醛计)'] },
      { key: 28, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: '紫外透光率/%', name: '220nm', nameSearchValue: ['紫外透过率(220nm)'] },
      { key: 29, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: '紫外透光率/%', name: '275nm', nameSearchValue: ['紫外透过率(275nm)'] },
      { key: 30, sampleRowSpan: 0, sampleName: '乙二醇', sampleSearchValue: ['工业用乙二醇'], item: '紫外透光率/%', name: '350nm', nameSearchValue: ['紫外透过率(350nm)'] },
      { key: 31, sampleRowSpan: 4, sampleName: '二乙二醇', sampleSearchValue: ['工业用二乙二醇'], item: '沸程/℃', itemRowSpan: 2, name: '初馏点', nameSearchValue: ['初馏点'] },
      { key: 32, sampleRowSpan: 0, sampleName: '二乙二醇', sampleSearchValue: ['工业用二乙二醇'], item: '沸程/℃', itemRowSpan: 0, name: '干点', nameSearchValue: ['干点'] },
      { key: 33, sampleRowSpan: 0, sampleName: '二乙二醇', sampleSearchValue: ['工业用二乙二醇'], item: null, name: '乙二醇含量/%（质量分数）', nameSearchValue: ['乙二醇'] },
      { key: 34, sampleRowSpan: 0, sampleName: '二乙二醇', sampleSearchValue: ['工业用二乙二醇'], item: null, name: '三乙二醇含量/%（质量分数））', nameSearchValue: ['三乙二醇'] },
      { key: 35, sampleRowSpan: 1, sampleName: '三乙二醇', sampleSearchValue: ['工业用三乙二醇'], item: null, name: '三乙二醇含量/%（质量分数）', nameSearchValue: ['三乙二醇'] },
    ],
  },
];

